# --- Circuit Breaker ---
resilience4j.circuitbreaker.instances.pdpService.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.pdpService.slidingWindowSize=10
resilience4j.circuitbreaker.instances.pdpService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.pdpService.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.pdpService.permittedNumberOfCallsInHalfOpenState=3

# --- Retry ---
resilience4j.retry.instances.transientDataAccess.maxAttempts=3
resilience4j.retry.instances.transientDataAccess.waitDuration=2s
resilience4j.retry.instances.transientDataAccess.retryExceptions[0]=org.springframework.dao.TransientDataAccessException
# https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/dao/TransientDataAccessException.html

resilience4j.retry.instances.httpServer.maxAttempts=3
resilience4j.retry.instances.httpServer.waitDuration=2s
resilience4j.retry.instances.httpServer.retryExceptions[0]=org.springframework.web.client.HttpServerErrorException
# https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/HttpServerErrorException.html

resilience4j.retry.instances.mailRetry.maxAttempts=3
resilience4j.retry.instances.mailRetry.waitDuration=2s
resilience4j.retry.instances.mailRetry.retryExceptions[0]=org.springframework.mail.MailConnectException
resilience4j.retry.instances.mailRetry.retryExceptions[1]=org.springframework.mail.MailSendException

# --- Rate Limiter ---
resilience4j.ratelimiter.instances.authService.limitForPeriod=5
resilience4j.ratelimiter.instances.authService.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.authService.timeoutDuration=0