<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
          <groupId>com.minewaku.chatter</groupId>
          <artifactId>message</artifactId>
          <version>1.0-SNAPSHOT</version>
    </parent>


    <artifactId>message-infrastructure</artifactId>


    <properties>
    	<jsonwebtoken.version>0.13.0</jsonwebtoken.version>
      <debezium.version>3.1.3.Final</debezium.version>
      <cloudinary.version>1.39.0</cloudinary.version>
      <java-uuid-generator.version>5.0.0</java-uuid-generator.version>
      <cassandra-jdbc-wrapper.version>5.0.0</cassandra-jdbc-wrapper.version>
    </properties>


    <dependencies>
      <dependency>
            <groupId>com.minewaku.chatter</groupId>
            <artifactId>message-application</artifactId>
            <version>${project.version}</version>
      </dependency>

      <dependency>
            <groupId>com.minewaku.chatter</groupId>
            <artifactId>message-domain</artifactId>
            <version>${project.version}</version>
      </dependency>



      <!-- Source: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-webmvc -->
      <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-webmvc</artifactId>
      </dependency>

      <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-validation -->
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-validation</artifactId>
      </dependency>

      <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-redis -->
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-data-redis</artifactId>
      </dependency>

      <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-log4j2 -->
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-log4j2</artifactId>
      </dependency>

      <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-security -->
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-security</artifactId>
      </dependency>

      <!-- Source: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-oauth2-resource-server -->
      <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-oauth2-resource-server</artifactId>
      </dependency>

      <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-integration -->
      <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-integration</artifactId>
      </dependency>
      
      <!-- Source: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-kafka -->
      <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-kafka</artifactId>
      </dependency>

      <!-- Source: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-cassandra -->
      <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-data-cassandra</artifactId>
      </dependency>
      
      <!-- Source: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-websocket -->
      <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-websocket</artifactId>
          <scope>compile</scope>
      </dependency>



      <!-- 
        *** VAULT PACKAGES ***
      -->
      <!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-vault-config -->
      <dependency>
          <groupId>org.springframework.cloud</groupId>
          <artifactId>spring-cloud-starter-vault-config</artifactId>
      </dependency>

      <!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-vault-config-databases -->
      <!-- 4.3.0 -->
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-vault-config-databases</artifactId>
      </dependency>
      
      <!-- https://mvnrepository.com/artifact/org.springframework.vault/spring-vault-core -->
      <dependency>
          <groupId>org.springframework.vault</groupId>
          <artifactId>spring-vault-core</artifactId>
      </dependency>



      <!-- 
        *** DATABASE MIGRATION PACKAGES ***
      -->
      <!-- Source: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-flyway -->
      <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-flyway</artifactId>
      </dependency>

      <!-- Source: https://mvnrepository.com/artifact/org.flywaydb/flyway-database-postgresql -->
      <dependency>
          <groupId>org.flywaydb</groupId>
          <artifactId>flyway-database-postgresql</artifactId>
      </dependency>

      <!-- Source: https://mvnrepository.com/artifact/org.flywaydb/flyway-database-cassandra -->
      <dependency>
          <groupId>org.flywaydb</groupId>
          <artifactId>flyway-database-cassandra</artifactId>
      </dependency>

      <!-- Source: https://mvnrepository.com/artifact/com.ing.data/cassandra-jdbc-wrapper -->
      <dependency>
          <groupId>com.ing.data</groupId>
          <artifactId>cassandra-jdbc-wrapper</artifactId>
          <version>${cassandra-jdbc-wrapper.version}</version>
          <scope>runtime</scope>
      </dependency>



      <!-- Source: https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-jackson -->
      <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-jackson</artifactId>
      </dependency>



      <!-- 
        *** TOKEN RELATED PACKAGES ***
      -->
      <!-- https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-api -->
      <dependency>
          <groupId>io.jsonwebtoken</groupId>
          <artifactId>jjwt-api</artifactId>
          <version>${jsonwebtoken.version}</version>
      </dependency>
      
      <!-- https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-impl -->
      <dependency>
          <groupId>io.jsonwebtoken</groupId>
          <artifactId>jjwt-impl</artifactId>
          <version>${jsonwebtoken.version}</version>
          <scope>runtime</scope>
      </dependency>

      <!-- https://mvnrepository.com/artifact/io.jsonwebtoken/jjwt-jackson -->
      <dependency>
          <groupId>io.jsonwebtoken</groupId>
          <artifactId>jjwt-jackson</artifactId>
          <version>${jsonwebtoken.version}</version>
          <scope>runtime</scope>
      </dependency>



      <!-- 
        *** DEBEZIUM RELLATED PACKAGES ***
      -->
      <!-- Source: https://mvnrepository.com/artifact/io.debezium/debezium-embedded -->
      <dependency>
          <groupId>io.debezium</groupId>
          <artifactId>debezium-embedded</artifactId>
          <version>${debezium.version}</version>
      </dependency>

      <!-- https://mvnrepository.com/artifact/io.debezium/debezium-api -->
      <dependency>
          <groupId>io.debezium</groupId>
          <artifactId>debezium-api</artifactId>
          <version>${debezium.version}</version>
      </dependency>

      <!-- https://mvnrepository.com/artifact/io.debezium/debezium-scripting -->
      <dependency>
          <groupId>io.debezium</groupId>
          <artifactId>debezium-scripting</artifactId>
          <version>${debezium.version}</version>
      </dependency>

      <!-- https://mvnrepository.com/artifact/io.debezium/debezium-connector-postgres -->
      <dependency>
        <groupId>io.debezium</groupId>
        <artifactId>debezium-connector-postgres</artifactId>
        <version>${debezium.version}</version>
      </dependency>

      <!-- https://mvnrepository.com/artifact/org.springframework.integration/spring-integration-debezium -->
      <dependency>
          <groupId>org.springframework.integration</groupId>
          <artifactId>spring-integration-debezium</artifactId>
      </dependency>
      
      <!-- Source: https://mvnrepository.com/artifact/org.apache.groovy/groovy -->
      <dependency>
          <groupId>org.apache.groovy</groupId>
          <artifactId>groovy</artifactId>
          <scope>compile</scope>
      </dependency>
      
      <!-- Source: https://mvnrepository.com/artifact/org.apache.groovy/groovy-jsr223 -->
      <dependency>
          <groupId>org.apache.groovy</groupId>
          <artifactId>groovy-jsr223</artifactId>
          <scope>compile</scope>
      </dependency>
      


      <!-- 
        *** UUID GENERATOR PACKAGES ***
      -->
      <!-- https://mvnrepository.com/artifact/com.fasterxml.uuid/java-uuid-generator -->
      <dependency>
        <groupId>com.fasterxml.uuid</groupId>
        <artifactId>java-uuid-generator</artifactId>
        <version>${java-uuid-generator.version}</version>
        <scope>compile</scope>
      </dependency>



      <!--
        CLOUDINARY PACKAGES
      -->
      <!-- https://mvnrepository.com/artifact/com.cloudinary/cloudinary-http44 -->
      <dependency>
        <groupId>com.cloudinary</groupId>
        <artifactId>cloudinary-http44</artifactId>
        <version>${cloudinary.version}</version>
      </dependency>



      <!--
        DATABASE DRIVER
      -->
      <dependency>
        <groupId>org.postgresql</groupId>
        <artifactId>postgresql</artifactId>
      </dependency>

    </dependencies>

</project>