# ==============================
# Import other configurations
# ==============================
spring.config.import=optional:file:.env[.properties],optional:classpath:resilience4j.properties,vault://

# ==============================
# Jackson Configuration
# ==============================
# spring.jackson.mapper.propagate-transient-marker=true
# spring.jackson.deserialization.fail-on-unknown-properties=false
# spring.jackson.serialization.write-dates-as-timestamps=false

# ==============================
# Application Configuration
# ==============================
server.port=${SERVER_PORT:5010}
worker.id=${WORKER_ID:10}
spring.application.name=message
spring.security.user.name=${SECURITY_USER:admin}
spring.security.user.password=${SECURITY_PASSWORD:123456}
springdotenv.directory=../


# ==============================
# Devtools Configuration
# ==============================
spring.devtools.restart.enabled=true

# ==============================
# Kafka Configuration
# ==============================
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:5003}

# ==============================
# Redis Configuration
# ==============================
spring.data.redis.username=${redis.username:default}
spring.data.redis.password=${redis.password:default}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6389}
spring.data.redis.ssl.enabled=${REDIS_SSL_ENABLED:false}

# ==============================
# ScyllaDB / Cassandra Config
# ==============================
spring.cassandra.contact-points=${SCYLLA_HOST:127.0.0.1}
spring.cassandra.port=${SCYLLA_PORT:9052}
spring.cassandra.keyspace-name=${SCYLLA_KEYSPACE:chatter}
spring.cassandra.username=${SCYLLA_USERNAME:cassandra}
spring.cassandra.password=${SCYLLA_PASSWORD:cassandra}
spring.cassandra.local-datacenter=${SCYLLA_DATACENTER:datacenter1}
spring.cassandra.schema-action=create-if-not-exists
spring.cassandra.request.timeout=10s
spring.cassandra.connection.connect-timeout=10s
spring.cassandra.connection.init-query-timeout=10s
spring.cassandra.pool.heartbeat-interval=30s

# ==============================
# Flyway Configuration
# ==============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.clean-disabled=false

# ==============================
# Cassandra Migration Configuration
# ==============================
cassandra.migration.keyspace-name=${SCYLLA_KEYSPACE:chatter}
cassandra.migration.script-location=classpath:cassandra/migration
cassandra.migration.strategy=IGNORE_DUPLICATES
cassandra.migration.consistency-level.ddl=LOCAL_QUORUM


# ==============================
# DataSource
# ==============================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5442}/${DB_NAME:chatter}?sslmode=disable
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=${DB_MAX_POOL_SIZE:10}
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.register-mbeans=true


# ==============================
# Eureka / Discovery
# ==============================
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
spring.cloud.inetutils.preferred-networks=${PREFERRED_NETWORKS:127.0.0.1}
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:5000/eureka}
eureka.client.healthcheck.enabled=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true


# ==============================
# Vault Configuration
# ==============================
spring.cloud.vault.host=${VAULT_HOST:localhost}
spring.cloud.vault.port=${VAULT_PORT:5002}
spring.cloud.vault.scheme=${VAULT_SCHEME:http}
spring.cloud.vault.authentication=TOKEN
spring.cloud.vault.token=${VAULT_TOKEN:dev-root-token}


# ==============================
# Vault Database Secrets Engine For Database
# ==============================
spring.cloud.vault.database.enabled=true
spring.cloud.vault.database.backend=database
spring.cloud.vault.database.role=message-postgresql-approle
spring.cloud.vault.database.username-property=spring.datasource.username
spring.cloud.vault.database.password-property=spring.datasource.password

# ==============================
# Vault Database Secrets Engine For Cassandra
# ==============================
spring.cloud.vault.cassandra.enabled=true
spring.cloud.vault.cassandra.backend=cassandra
spring.cloud.vault.cassandra.role=message-cassandra-approle
spring.cloud.vault.cassandra.username-property=spring.cassandra.username
spring.cloud.vault.cassandra.password-property=spring.cassandra.password


# ==============================
# Vault Config Lifecycle Management
# ==============================
spring.cloud.vault.config.lifecycle.enabled=true
spring.cloud.vault.config.lifecycle.min-renewal=15m
spring.cloud.vault.config.lifecycle.expiry-threshold=30m
spring.cloud.vault.config.lifecycle.lease-endpoints=leases
spring.cloud.vault.config.lifecycle.lease-strategy=retainonerror


# ==============================
# Vault KV (Key-Value) Secrets Engine
# ==============================
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.default-context=common/jwt/rs256
# if does not set implicitly, the default path would be spring.cloud.vault.kv.backend + spring.application.name
spring.cloud.vault.kv.application-name=message


# ==============================
# Logging Configuration
# ==============================
logging.config=classpath:log4j2.properties

# ==============================
# Spring Boot Actuator Configuration
# ==============================
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics,loggers,env
