# --- Circuit Breaker ---
resilience4j.circuitbreaker.instances.cloudinary.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.cloudinary.slidingWindowSize=10
resilience4j.circuitbreaker.instances.cloudinary.failureRateThreshold=50
resilience4j.circuitbreaker.instances.cloudinary.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.cloudinary.permittedNumberOfCallsInHalfOpenState=3


# --- Retry ---
#transientDataAccess
resilience4j.retry.instances.transientDataAccess.maxAttempts=3
resilience4j.retry.instances.transientDataAccess.waitDuration=2s
resilience4j.retry.instances.transientDataAccess.retryExceptions[0]=org.springframework.dao.TransientDataAccessException
# https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/dao/TransientDataAccessException.html


#mailRery
resilience4j.retry.instances.mailRetry.maxAttempts=3
resilience4j.retry.instances.mailRetry.waitDuration=2s
# 1. Catch temporary sending failures (e.g., SMTP server connection drops, timeouts, or rate limits)
resilience4j.retry.instances.mailRetry.retryExceptions[0]=org.springframework.mail.MailSendException
# 2. Catch low-level network timeouts when trying to reach the SMTP server
resilience4j.retry.instances.mailRetry.retryExceptions[1]=java.net.SocketTimeoutException
# 3. Catch general I/O exceptions in case the underlying JavaMail API throws raw connection errors
resilience4j.retry.instances.mailRetry.retryExceptions[2]=java.io.IOException


#httpServer
resilience4j.retry.instances.httpServer.maxAttempts=3
resilience4j.retry.instances.httpServer.waitDuration=2s
# 1. Catch 5xx errors returned by the target server (Overload, Bad Gateway, etc.)
resilience4j.retry.instances.httpServer.retryExceptions[0]=org.springframework.web.client.HttpServerErrorException
# 2. Catch network failures, connection drops, or timeouts before reaching the server (Crucial!)
resilience4j.retry.instances.httpServer.retryExceptions[1]=org.springframework.web.client.ResourceAccessException
# 3. (Optional) Catch general I/O exceptions in case other libraries don't wrap them in ResourceAccessException
resilience4j.retry.instances.httpServer.retryExceptions[2]=java.io.IOException
resilience4j.retry.instances.httpServer.retryExceptions[2]=com.minewaku.chatter.message.infrastructure.exception.FileStorageException
# https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/HttpServerErrorException.html

# --- Rate Limiter ---
resilience4j.ratelimiter.instances.authService.limitForPeriod=5
resilience4j.ratelimiter.instances.authService.limitRefreshPeriod=1s
resilience4j.ratelimiter.instances.authService.timeoutDuration=0