# ==============================
# Import other configurations
# ==============================
spring.config.import=vault://

# ==============================
# Application Configuration
# ==============================
server.port=${SERVER_PORT:5001}
spring.application.name=apigateway
spring.security.user.name=${SECURITY_USER:admin}
spring.security.user.password=${SECURITY_PASSWORD:123456}

# ==============================
# Gateway Configuration
# ==============================
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

# ==============================
# Redis Configuration
# ==============================
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6380}
spring.data.redis.ssl.enabled=${REDIS_SSL_ENABLED:false}

# ==============================
# Eureka / Discovery
# ==============================
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
spring.cloud.inetutils.preferred-networks=${PREFERRED_NETWORKS:127.0.0.1}
eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://localhost:5000/eureka}
eureka.client.healthcheck.enabled=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# ==============================
# Vault Configuration
# ==============================
spring.cloud.vault.host=${VAULT_HOST:localhost}
spring.cloud.vault.port=${VAULT_PORT:5002}
spring.cloud.vault.scheme=${VAULT_SCHEME:http}
spring.cloud.vault.authentication=TOKEN
spring.cloud.vault.token=${VAULT_TOKEN:dev-root-token}

# ==============================
# Vault Config Lifecycle Management
# ==============================
spring.cloud.vault.config.lifecycle.enabled=true
spring.cloud.vault.config.lifecycle.min-renewal=15m
spring.cloud.vault.config.lifecycle.expiry-threshold=30m
spring.cloud.vault.config.lifecycle.lease-endpoints=leases
spring.cloud.vault.config.lifecycle.lease-strategy=retainonerror

# ==============================
# Vault KV (Key-Value) Secrets Engine
# ==============================
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.default-context=common/jwt/rs256
# if does not set implicitly, the default path would be spring.cloud.vault.kv.backend + spring.application.name
spring.cloud.vault.kv.application-name=apigateway

# ==============================
# Logging Configuration
# ==============================
logging.config=classpath:log4j2.properties

# ==============================
# Spring Boot Actuator Configuration
# ==============================
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics,loggers,env